server:
  port: 8001
 
# 数据源配置
spring:
  application: 
    name: provider-service
    
eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: provider-service  #客户端服务名
    instance-id: provider-service:8001 #客户端实例名称
    prefer-ip-address: true #显示IP
  client: 
    service-url: 
      # 单机 defaultZone: http://localhost:2001/eureka   #把服务注册到eureka注册中心
      defaultZone: http://localhost:7001/eureka/
